apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  labels:
    app: patient-service
spec:
  selector:
    matchLabels:
      app: patient-service
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: patient-service
        image: 539935451710.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
